baseurl = "https://petra66orii.github.io/undercoverunicorn/"
enableEmoji = true
theme = "hugo-classic"
title = "Undercover Unicorn"
footnotereturnlinkcontents = "↩"
languageCode = "en-us"


[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 1
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2


[params]
custom_css = ["css/style.css", "css/fonts.css", "css/theme-override.css"]
staticDir = ["static"]
description = "A simple, minimal blog for those who love text."
footer = "[Github](https://github.com/petra66orii) | [LinkedIn](https://www.linkedin.com/in/petra-bot-a552601a4/)"